"""Generate or collect every figure used by the report and slides.

Run from the repository root:
    python scripts/make_report_figures.py
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.compare_baselines import (  # noqa: E402
    compare_results,
    load_result,
    plot_overall_comparison,
    plot_per_joint_comparison,
)
from src.config import load_config, project_path  # noqa: E402
from src.data.coco_dataset import build_coco_datasets  # noqa: E402
from src.data.transforms import denormalize_image  # noqa: E402
from src.visualization.visualize import plot_training_curves  # noqa: E402


REPORT_FIGURES = PROJECT_ROOT / "report" / "figures"
EXPECTED_OUTPUTS = (
    "training_loss_curve.png",
    "pck_comparison.png",
    "per_joint_pck.png",
    "success_cases.png",
    "failure_cases.png",
    "target_heatmap_example.png",
)


class FigureGenerationError(Exception):
    """Raised when a required saved artifact is unavailable or invalid."""


def parse_args() -> argparse.Namespace:
    """Parse command-line options."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        default="configs/coco_simplebaseline.yaml",
        help="YAML configuration path relative to the repository root.",
    )
    parser.add_argument(
        "--device",
        choices=("auto", "cpu", "cuda"),
        default="auto",
        help="Device used only when prediction figures must be regenerated.",
    )
    return parser.parse_args()


def _require_file(path: Path, description: str) -> None:
    if not path.is_file():
        raise FigureGenerationError(f"{description} not found: {path}")


def _load_history(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as history_file:
            history = json.load(history_file)
    except json.JSONDecodeError as error:
        raise FigureGenerationError(
            f"Training history is not valid JSON: {path} ({error})"
        ) from error
    if not isinstance(history, dict) or not all(
        isinstance(history.get(key), list) and history[key]
        for key in ("train_loss", "val_loss")
    ):
        raise FigureGenerationError(
            f"Training history must contain non-empty train_loss and "
            f"val_loss lists: {path}"
        )
    return history


def _find_loss_source(config: dict[str, Any]) -> tuple[str, Path]:
    output = config["output"]
    history_path = project_path(Path(output["dir"]) / output["history"])
    if history_path.is_file():
        return "history", history_path

    candidates = (
        REPORT_FIGURES / output["loss_curves"],
        project_path(Path(output.get("figures_dir", output["dir"])))
        / output["loss_curves"],
        project_path(Path(output["dir"]) / output["loss_curves"]),
    )
    for candidate in candidates:
        if candidate.is_file():
            return "figure", candidate
    raise FigureGenerationError(
        "No saved training history or loss figure was found. Expected one "
        f"of: {history_path}, " + ", ".join(str(path) for path in candidates)
    )


def _prediction_figures_need_regeneration() -> bool:
    return any(
        not (REPORT_FIGURES / name).is_file()
        for name in ("success_cases.png", "failure_cases.png")
    )


def _preflight(config: dict[str, Any]) -> tuple[str, Path]:
    _require_file(
        REPORT_FIGURES / "pck_results.json",
        "Final SimpleBaseline PCK result",
    )
    _require_file(
        REPORT_FIGURES / "trivial_baseline_pck.json",
        "Final Average-Pose PCK result",
    )
    loss_source = _find_loss_source(config)

    if _prediction_figures_need_regeneration():
        output = config["output"]
        weights_path = project_path(Path(output["dir"]) / output["weights"])
        if not weights_path.is_file():
            raise FigureGenerationError(
                "Success/failure figures are missing and the configured "
                f"checkpoint was not found: {weights_path}\n"
                "Restore the saved checkpoint or add both report figures "
                "generated by scripts/visualize_predictions.py."
            )
    return loss_source


def _make_loss_figure(
    config: dict[str, Any],
    source_kind: str,
    source_path: Path,
) -> None:
    destination = REPORT_FIGURES / "training_loss_curve.png"
    if source_kind == "history":
        plot_training_curves(
            _load_history(source_path),
            destination,
            unfreeze_epoch=int(config["training"]["unfreeze_epoch"]),
        )
    elif source_path.resolve() != destination.resolve():
        shutil.copy2(source_path, destination)


def _make_pck_figures() -> None:
    trivial_path = REPORT_FIGURES / "trivial_baseline_pck.json"
    simple_path = REPORT_FIGURES / "pck_results.json"
    comparison = compare_results(
        load_result(trivial_path, "Average-Pose result"),
        load_result(simple_path, "SimpleBaseline result"),
        trivial_path,
        simple_path,
    )
    plot_overall_comparison(
        comparison,
        REPORT_FIGURES / "pck_comparison.png",
    )
    plot_per_joint_comparison(
        comparison,
        REPORT_FIGURES / "per_joint_pck.png",
    )


def _make_prediction_figures(args: argparse.Namespace) -> None:
    if not _prediction_figures_need_regeneration():
        return
    command = [
        sys.executable,
        str(PROJECT_ROOT / "scripts" / "visualize_predictions.py"),
        "--config",
        args.config,
        "--device",
        args.device,
    ]
    try:
        subprocess.run(command, cwd=PROJECT_ROOT, check=True)
    except subprocess.CalledProcessError as error:
        raise FigureGenerationError(
            "Could not regenerate success/failure prediction figures; "
            "scripts/visualize_predictions.py failed."
        ) from error


def _make_target_heatmap(config: dict[str, Any]) -> None:
    data = config["data"]
    _, val_dataset = build_coco_datasets(
        data_dir=project_path(data["dir"]),
        input_size=data["input_size"],
        heatmap_size=data["heatmap_size"],
        sigma=data["sigma"],
        train_fraction=data["train_fraction"],
        split_seed=data["split_seed"],
        min_image_keypoints=data["min_image_keypoints"],
        min_annotation_keypoints=data["min_annotation_keypoints"],
        download=data["download"],
    )
    if len(val_dataset) == 0:
        raise FigureGenerationError(
            "The validation dataset is empty; cannot render a target heatmap."
        )

    image, heatmaps = val_dataset[0]
    visible = heatmaps.reshape(heatmaps.shape[0], -1).max(dim=1).values > 0
    if not visible.any():
        raise FigureGenerationError(
            "The selected validation sample has no visible target heatmaps."
        )
    combined_heatmap = heatmaps[visible].max(dim=0).values.numpy()
    display_image = denormalize_image(image).permute(1, 2, 0).numpy()

    figure, axes = plt.subplots(1, 2, figsize=(9, 4))
    axes[0].imshow(np.clip(display_image, 0, 1))
    axes[0].set_title("Person crop")
    axes[0].axis("off")
    axes[1].imshow(combined_heatmap, cmap="magma", vmin=0, vmax=1)
    axes[1].set_title("Target keypoint heatmaps")
    axes[1].axis("off")
    figure.tight_layout()
    figure.savefig(
        REPORT_FIGURES / "target_heatmap_example.png",
        dpi=140,
        bbox_inches="tight",
    )
    plt.close(figure)


def run(args: argparse.Namespace) -> None:
    """Generate report figures without changing persisted metric values."""
    config_path = project_path(args.config)
    _require_file(config_path, "Configuration")
    config = load_config(config_path)
    loss_source_kind, loss_source_path = _preflight(config)
    REPORT_FIGURES.mkdir(parents=True, exist_ok=True)

    _make_loss_figure(config, loss_source_kind, loss_source_path)
    _make_pck_figures()
    _make_prediction_figures(args)
    _make_target_heatmap(config)

    missing = [
        str(REPORT_FIGURES / name)
        for name in EXPECTED_OUTPUTS
        if not (REPORT_FIGURES / name).is_file()
    ]
    if missing:
        raise FigureGenerationError(
            "Figure generation finished with missing outputs: "
            + ", ".join(missing)
        )
    print("Report figures ready:")
    for name in EXPECTED_OUTPUTS:
        print(f"  {REPORT_FIGURES / name}")


def main() -> int:
    """Run the workflow and show expected failures without a traceback."""
    try:
        run(parse_args())
    except (FigureGenerationError, OSError, KeyError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
